using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using System;

[Serializable]
public class datosextra
{

    public int completaalien1v;
    public int completaalien1m;
    public int alien1huevooculto;
    public int alien1muere;
    public int alien1secretobajoelasteroide;
    public int alien1saladelrey;
    public int alien1salasecreta;
    public int alien1mejora1;
    public int alien1mejora2;
    public int alien1mejora3;
    public int alien1mejora4;
    public int alien1mejora5;
    public int alien1consigue1gema;
    public int alien1consigue10monedas;
    public int alien1consigue50monedas;
    public int alien1consiguelagrangema;
    public int alien1consigue15gemas;
    public int alien1usaelcochedelmundo;
    public int alien1usalanaveenelespacio;
    public int alien1visitaotroasteroide;
    public int alien1primeracinematica;
    public int completaalien2v;
    public int completaalien3v;
    public int alien2huevooculto;
    public int alien2muere;
    public int alien2ahorra1000monedas;
    public int alien2obtentodaslasmejorasvida;
    public int alien2saladelrey;
    public int alien2compraentodaslastiendas1vez;
    public int alien2sacaelfinalalternativo;
    public int alien2mejora1;
    public int alien2mejora2;
    public int alien2mejora3;
    public int alien2mejora4;
    public int alien2mejora5;
    public int alien2hablarcontumujer;
    public int alien2primeracinematica;
    public int alien2unapaginadeldiario;
    public int alien2consigue4llaves;
    public int alien2consiguetodaslaspaginas;
    public int alien2escuchaunapaginadeldiario;
    public int alien2usaelcochedelmundo;
    public int alien2hipnotizaunpirata;
    public int alien2abrelatiendabloqueadadelaprimerazona;
    public int alien2encuentralatiendaocultadelasegundazona;
    public int alien2usalanavegumi;
    public int alien2desbloqueatodosloscheckpoits;
    public int alien2desbloqueaelcheckpoint1delnivel1;
    public int alien2usaelsaltador;
    public int alien2usaelacelerador;
    public int completaalien2m;
    public int completaalien3m;
    public int alien3huevooculto;
    public int alien3consiguetodaslasarmas;
    public int alien3ahorra5000monedas;
    public int alien3consiguetodaslasarmaduras;
    public int alien3acabaeltutorial;
    public int alien3vence100enemigos;
    public int alien3vence200enemigos;
    public int alien3consiguetodadlasmejorasvida;
    public int alien3gastatodalamuniciondetodaslasarmas;
    public int alien3muere;
    public int alien3aceptalaherencia;
    public int alien3jefe1;
    public int alien3jefe2;
    public int alien3jefe3;
    public int alien3jefe4;
    public int alien3jefe5;
    public int alien3jefe6;
    public int alien3jefe1nave;
    public int alien3jefe5nave;
    public int alien3primeramejoradevida;
    public int alien3primeraarma;
    public int alien3primeraarmadura;
    public int alien3entraalmenuextras;
    public int alien3entraalaguiadelpause;
    public int alien3entraaseleccionrapidaenelpause;
    public int alien3consiguetodaslaspaginas;
    public int alien3escuchaunapagina;
    public int alien3consigue10gemas;
    public int alien3consigue20gemas;
    public int alien3consigue40gemas;
    public int alien3consigue70gemas;
    public int alien3consigue100gemas;
    public int alien3compraladestructora;
    public int alien3planeta1nave;
    public int alien3planeta2nave;
    public int alien3planeta3nave;
    public int alien3planeta4nave;
    public int alien3planeta5nave;
    public int alien3planeta6nave;
    public int alien3planeta7nave;
    public int alien3planeta8nave;
    public int alien3planeta9nave;
    public int alien3planeta10nave;
    public int alien3planeta11nave;
    public int alien3planeta12nave;
    public int alien3planeta13nave;
    public int alien3planeta14nave;
    public int alien3planeta15nave;
    public int alien3planeta16nave;
    public int alien3planeta17nave;

}
